-- Medicine Master Database with 100 Essential Medicines
-- Insert data for medicine_master table
-- Updated to match the correct database schema

INSERT INTO medicine_master (
  generic_name, brand_name, manufacturer, strength, dosage_form, composition,
  therapeutic_class, pharmacological_class, schedule, pack_size, mrp,
  category, indications, contraindications, side_effects, drug_interactions,
  storage_conditions, expiry_period, is_active
) VALUES

-- Pain & Inflammation (10 medicines)
('Ibuprofen', 'Advil', 'Pfizer', '400mg', 'Tablet', 'Ibuprofen 400mg', 'Anti-inflammatory', 'NSAID', 'OTC', '10 tablets', 45.00, 'Analgesic', 'Pain, Inflammation, Fever', 'Peptic ulcer, Severe heart failure', 'GI upset, Dizziness', 'Warfarin, ACE inhibitors', 'Store at room temperature', '3 years', TRUE),
('Aspirin', 'Disprin', 'Bayer', '325mg', 'Tablet', 'Acetylsalicylic acid 325mg', 'Antiplatelet', 'NSAID', 'OTC', '10 tablets', 25.00, 'Analgesic', 'Cardiovascular protection, Pain, Fever', 'Children under 16 years, Active bleeding', 'GI bleeding, Tinnitus', 'Warfarin, Methotrexate', 'Store in dry place', '2 years', TRUE),
('Diclofenac', 'Voltaren', 'Novartis', '50mg', 'Tablet', 'Diclofenac sodium 50mg', 'Anti-inflammatory', 'NSAID', 'Prescription', '10 tablets', 35.00, 'Analgesic', 'Arthritis, Post-operative pain', 'Severe cardiac disease, Active GI bleeding', 'Headache, Dizziness, GI upset', 'Lithium, Digoxin', 'Store below 30°C', '3 years', TRUE),
('Tramadol', 'Ultram', 'Johnson & Johnson', '50mg', 'Tablet', 'Tramadol HCl 50mg', 'Analgesic', 'Opioid analgesic', 'Prescription', '10 tablets', 65.00, 'Analgesic', 'Moderate to severe pain', 'Seizure disorders, MAO inhibitor use', 'Nausea, Dizziness, Constipation', 'MAO inhibitors, SSRIs', 'Store at room temperature', '3 years', TRUE),
('Naproxen', 'Aleve', 'Bayer', '250mg', 'Tablet', 'Naproxen sodium 250mg', 'Anti-inflammatory', 'NSAID', 'OTC', '10 tablets', 40.00, 'Analgesic', 'Arthritis, Menstrual pain', 'Active peptic ulcer, Severe renal impairment', 'Headache, Drowsiness', 'Warfarin, Methotrexate', 'Store at room temperature', '3 years', TRUE),
('Paracetamol', 'Panadol', 'GSK', '500mg', 'Tablet', 'Acetaminophen 500mg', 'Analgesic', 'Non-NSAID analgesic', 'OTC', '10 tablets', 20.00, 'Analgesic', 'Pain, Fever', 'Severe liver disease', 'Rare: Liver toxicity', 'Warfarin (high doses)', 'Store below 25°C', '3 years', TRUE),
('Acetaminophen', 'Tylenol', 'Johnson & Johnson', '500mg', 'Tablet', 'Acetaminophen 500mg', 'Analgesic', 'Non-NSAID analgesic', 'OTC', '20 tablets', 35.00, 'Analgesic', 'Pain, Fever', 'Severe liver disease', 'Rare: Liver toxicity', 'Warfarin (high doses)', 'Store at room temperature', '4 years', TRUE),
('Celecoxib', 'Celebrex', 'Pfizer', '100mg', 'Capsule', 'Celecoxib 100mg', 'Anti-inflammatory', 'COX-2 selective', 'Prescription', '10 capsules', 85.00, 'Analgesic', 'Osteoarthritis, Rheumatoid arthritis', 'Sulfonamide allergy, Active GI bleeding', 'Headache, Hypertension', 'Warfarin, ACE inhibitors', 'Store at room temperature', '3 years', TRUE),
('Ketorolac', 'Toradol', 'Roche', '10mg', 'Tablet', 'Ketorolac tromethamine 10mg', 'Anti-inflammatory', 'NSAID', 'Prescription', '10 tablets', 55.00, 'Analgesic', 'Post-operative pain, Acute pain', 'Peptic ulcer, Renal impairment', 'GI upset, Drowsiness', 'Anticoagulants', 'Store at room temperature', '3 years', TRUE),
('Morphine', 'MS Contin', 'Purdue Pharma', '15mg', 'Tablet', 'Morphine sulfate 15mg', 'Narcotic analgesic', 'Opioid analgesic', 'Schedule II', '10 tablets', 120.00, 'Analgesic', 'Severe pain', 'Respiratory depression, Paralytic ileus', 'Sedation, Respiratory depression', 'CNS depressants, MAO inhibitors', 'Store securely at room temp', '3 years', TRUE),

-- Antibiotics (15 medicines)
('Amoxicillin', 'Amoxil', 'GSK', '500mg', 'Capsule', 'Amoxicillin trihydrate 500mg', 'Antibiotic', 'Penicillin', 'Prescription', '21 capsules', 75.00, 'Antibiotic', 'Respiratory infections, UTI', 'Penicillin allergy', 'Diarrhea, Nausea', 'Warfarin', 'Store below 25°C', '3 years', TRUE),
('Cephalexin', 'Keflex', 'Lilly', '250mg', 'Capsule', 'Cephalexin monohydrate 250mg', 'Antibiotic', 'Cephalosporin', 'Prescription', '28 capsules', 85.00, 'Antibiotic', 'Skin infections, UTI', 'Cephalosporin allergy', 'Diarrhea, Nausea', 'Warfarin', 'Store at room temperature', '3 years', TRUE),
('Azithromycin', 'Zithromax', 'Pfizer', '250mg', 'Tablet', 'Azithromycin dihydrate 250mg', 'Antibiotic', 'Macrolide', 'Prescription', '6 tablets', 95.00, 'Antibiotic', 'Respiratory infections, Chlamydia', 'Macrolide allergy, Liver disease', 'Nausea, Diarrhea', 'Warfarin, Digoxin', 'Store at room temperature', '3 years', TRUE),
('Ciprofloxacin', 'Cipro', 'Bayer', '500mg', 'Tablet', 'Ciprofloxacin HCl 500mg', 'Antibiotic', 'Fluoroquinolone', 'Prescription', '14 tablets', 110.00, 'Antibiotic', 'UTI, Respiratory infections', 'Tendinitis history, Children <18 years', 'Nausea, Headache, Tendinitis', 'Warfarin, Theophylline', 'Store at room temperature', '3 years', TRUE),
('Doxycycline', 'Vibramycin', 'Pfizer', '100mg', 'Capsule', 'Doxycycline hyclate 100mg', 'Antibiotic', 'Tetracycline', 'Prescription', '14 capsules', 65.00, 'Antibiotic', 'Respiratory infections, Acne', 'Pregnancy, Children <8 years', 'Photosensitivity, GI upset', 'Warfarin, Iron', 'Store below 25°C', '3 years', TRUE),
('Metronidazole', 'Flagyl', 'Pfizer', '400mg', 'Tablet', 'Metronidazole 400mg', 'Antibiotic', 'Nitroimidazole', 'Prescription', '21 tablets', 45.00, 'Antibiotic', 'Anaerobic infections, H. pylori', 'First trimester pregnancy', 'Metallic taste, Nausea', 'Warfarin, Alcohol', 'Store at room temperature', '3 years', TRUE),
('Clindamycin', 'Cleocin', 'Pfizer', '150mg', 'Capsule', 'Clindamycin HCl 150mg', 'Antibiotic', 'Lincosamide', 'Prescription', '16 capsules', 75.00, 'Antibiotic', 'Skin infections, Dental infections', 'Colitis history', 'Diarrhea, Colitis', 'Neuromuscular blocking agents', 'Store at room temperature', '3 years', TRUE),
('Erythromycin', 'E-Mycin', 'Abbott', '250mg', 'Tablet', 'Erythromycin stearate 250mg', 'Antibiotic', 'Macrolide', 'Prescription', '28 tablets', 55.00, 'Antibiotic', 'Respiratory infections, Skin infections', 'Liver disease, Macrolide allergy', 'GI upset, Cramping', 'Warfarin, Theophylline', 'Store at room temperature', '3 years', TRUE),
('Ampicillin', 'Principen', 'Pfizer', '250mg', 'Capsule', 'Ampicillin trihydrate 250mg', 'Antibiotic', 'Penicillin', 'Prescription', '28 capsules', 50.00, 'Antibiotic', 'UTI, Respiratory infections', 'Penicillin allergy', 'Diarrhea, Rash', 'Warfarin', 'Store below 25°C', '3 years', TRUE),
('Trimethoprim', 'Proloprim', 'GSK', '100mg', 'Tablet', 'Trimethoprim 100mg', 'Antibiotic', 'Folate antagonist', 'Prescription', '14 tablets', 35.00, 'Antibiotic', 'UTI', 'Folate deficiency', 'Rash, GI upset', 'Warfarin', 'Store at room temperature', '3 years', TRUE),
('Nitrofurantoin', 'Macrobid', 'Procter & Gamble', '100mg', 'Capsule', 'Nitrofurantoin monohydrate 100mg', 'Antibiotic', 'Nitrofuran', 'Prescription', '14 capsules', 95.00, 'Antibiotic', 'UTI', 'Severe renal impairment', 'Nausea, Pulmonary toxicity', 'None significant', 'Store at room temperature', '3 years', TRUE),
('Vancomycin', 'Vancocin', 'Lilly', '125mg', 'Capsule', 'Vancomycin HCl 125mg', 'Antibiotic', 'Glycopeptide', 'Prescription', '20 capsules', 185.00, 'Antibiotic', 'C. difficile colitis, MRSA infections', 'Hypersensitivity', 'Nephrotoxicity, Ototoxicity', 'Aminoglycosides', 'Store at room temperature', '3 years', TRUE),
('Sulfamethoxazole/Trimethoprim', 'Bactrim', 'Roche', '400/80mg', 'Tablet', 'SMX 400mg/TMP 80mg', 'Antibiotic', 'Sulfonamide combination', 'Prescription', '20 tablets', 65.00, 'Antibiotic', 'UTI, PCP prophylaxis', 'Sulfonamide allergy, Severe renal impairment', 'Rash, GI upset', 'Warfarin, Methotrexate', 'Store at room temperature', '3 years', TRUE),
('Levofloxacin', 'Levaquin', 'Johnson & Johnson', '500mg', 'Tablet', 'Levofloxacin 500mg', 'Antibiotic', 'Fluoroquinolone', 'Prescription', '10 tablets', 125.00, 'Antibiotic', 'Respiratory infections, UTI', 'Tendinitis history', 'Nausea, Headache, Tendinitis', 'Warfarin, NSAIDs', 'Store at room temperature', '3 years', TRUE),
('Ceftriaxone', 'Rocephin', 'Roche', '1g', 'Injection', 'Ceftriaxone sodium 1g', 'Antibiotic', 'Cephalosporin', 'Prescription', '1 vial', 145.00, 'Antibiotic', 'Serious infections', 'Cephalosporin allergy', 'Diarrhea, Injection site reaction', 'Calcium-containing solutions', 'Store below 25°C', '3 years', TRUE),

-- Cardiovascular (12 medicines)
('Lisinopril', 'Prinivil', 'Merck', '10mg', 'Tablet', 'Lisinopril 10mg', 'Antihypertensive', 'ACE inhibitor', 'Prescription', '30 tablets', 85.00, 'Cardiovascular', 'Hypertension, Heart failure', 'Pregnancy, Bilateral renal stenosis', 'Dry cough, Hyperkalemia', 'Potassium supplements, NSAIDs', 'Store at room temperature', '3 years', TRUE),
('Atorvastatin', 'Lipitor', 'Pfizer', '20mg', 'Tablet', 'Atorvastatin calcium 20mg', 'Lipid-lowering', 'Statin', 'Prescription', '30 tablets', 195.00, 'Cardiovascular', 'Hypercholesterolemia, CAD prevention', 'Active liver disease, Pregnancy', 'Muscle pain, Elevated liver enzymes', 'Warfarin, Cyclosporine', 'Store at room temperature', '3 years', TRUE),
('Metoprolol', 'Lopressor', 'Novartis', '50mg', 'Tablet', 'Metoprolol tartrate 50mg', 'Antihypertensive', 'Beta-blocker', 'Prescription', '30 tablets', 75.00, 'Cardiovascular', 'Hypertension, Angina, Heart failure', 'Severe bradycardia, Cardiogenic shock', 'Fatigue, Dizziness', 'Insulin, Verapamil', 'Store at room temperature', '3 years', TRUE),
('Losartan', 'Cozaar', 'Merck', '50mg', 'Tablet', 'Losartan potassium 50mg', 'Antihypertensive', 'ARB', 'Prescription', '30 tablets', 95.00, 'Cardiovascular', 'Hypertension, Diabetic nephropathy', 'Pregnancy, Bilateral renal stenosis', 'Dizziness, Hyperkalemia', 'Potassium supplements', 'Store at room temperature', '3 years', TRUE),
('Furosemide', 'Lasix', 'Sanofi', '40mg', 'Tablet', 'Furosemide 40mg', 'Diuretic', 'Loop diuretic', 'Prescription', '30 tablets', 45.00, 'Cardiovascular', 'Edema, Heart failure', 'Anuria, Severe electrolyte depletion', 'Hypokalemia, Dehydration', 'Lithium, Digoxin', 'Store at room temperature', '3 years', TRUE),
('Digoxin', 'Lanoxin', 'GSK', '0.25mg', 'Tablet', 'Digoxin 0.25mg', 'Inotropic', 'Cardiac glycoside', 'Prescription', '30 tablets', 65.00, 'Cardiovascular', 'Heart failure, Atrial fibrillation', 'Ventricular arrhythmias, Heart block', 'Nausea, Visual disturbances', 'Quinidine, Amiodarone', 'Store at room temperature', '3 years', TRUE),
('Warfarin', 'Coumadin', 'Bristol Myers Squibb', '5mg', 'Tablet', 'Warfarin sodium 5mg', 'Anticoagulant', 'Vitamin K antagonist', 'Prescription', '30 tablets', 85.00, 'Cardiovascular', 'Atrial fibrillation, DVT, PE', 'Active bleeding, Pregnancy', 'Bleeding, Bruising', 'Aspirin, Antibiotics', 'Store at room temperature', '3 years', TRUE),
('Clopidogrel', 'Plavix', 'Sanofi', '75mg', 'Tablet', 'Clopidogrel bisulfate 75mg', 'Antiplatelet', 'P2Y12 inhibitor', 'Prescription', '30 tablets', 295.00, 'Cardiovascular', 'Acute coronary syndrome, Stroke prevention', 'Active bleeding, Severe liver disease', 'Bleeding, Bruising', 'Warfarin, PPIs', 'Store at room temperature', '3 years', TRUE),
('Simvastatin', 'Zocor', 'Merck', '20mg', 'Tablet', 'Simvastatin 20mg', 'Lipid-lowering', 'Statin', 'Prescription', '30 tablets', 125.00, 'Cardiovascular', 'Hypercholesterolemia', 'Active liver disease, Pregnancy', 'Muscle pain, Liver enzyme elevation', 'Warfarin, Amlodipine', 'Store at room temperature', '3 years', TRUE),
('Amlodipine', 'Norvasc', 'Pfizer', '5mg', 'Tablet', 'Amlodipine besylate 5mg', 'Antihypertensive', 'Calcium channel blocker', 'Prescription', '30 tablets', 75.00, 'Cardiovascular', 'Hypertension, Angina', 'Severe aortic stenosis', 'Ankle edema, Flushing', 'Simvastatin', 'Store at room temperature', '3 years', TRUE),
('Hydrochlorothiazide', 'Microzide', 'Watson', '25mg', 'Tablet', 'Hydrochlorothiazide 25mg', 'Diuretic', 'Thiazide diuretic', 'Prescription', '30 tablets', 35.00, 'Cardiovascular', 'Hypertension, Edema', 'Anuria, Sulfonamide allergy', 'Hypokalemia, Hyperuricemia', 'Lithium, Digoxin', 'Store at room temperature', '3 years', TRUE),
('Propranolol', 'Inderal', 'AstraZeneca', '40mg', 'Tablet', 'Propranolol HCl 40mg', 'Antihypertensive', 'Beta-blocker', 'Prescription', '30 tablets', 55.00, 'Cardiovascular', 'Hypertension, Angina, Migraine prophylaxis', 'Asthma, Heart block', 'Fatigue, Cold extremities', 'Insulin, Epinephrine', 'Store at room temperature', '3 years', TRUE),

-- Gastrointestinal (8 medicines)
('Omeprazole', 'Prilosec', 'AstraZeneca', '20mg', 'Capsule', 'Omeprazole 20mg', 'Proton pump inhibitor', 'PPI', 'Prescription', '30 capsules', 95.00, 'Gastrointestinal', 'GERD, Peptic ulcer', 'Hypersensitivity', 'Headache, Diarrhea', 'Warfarin, Clopidogrel', 'Store at room temperature', '3 years', TRUE),
('Ranitidine', 'Zantac', 'GSK', '150mg', 'Tablet', 'Ranitidine HCl 150mg', 'Acid reducer', 'H2 receptor antagonist', 'OTC', '30 tablets', 45.00, 'Gastrointestinal', 'Peptic ulcer, GERD', 'Hypersensitivity', 'Headache, Dizziness', 'Warfarin', 'Store at room temperature', '3 years', FALSE),
('Loperamide', 'Imodium', 'Johnson & Johnson', '2mg', 'Capsule', 'Loperamide HCl 2mg', 'Antidiarrheal', 'Opioid receptor agonist', 'OTC', '12 capsules', 35.00, 'Gastrointestinal', 'Acute diarrhea, Chronic diarrhea', 'Bloody diarrhea, Fever', 'Constipation, Drowsiness', 'None significant', 'Store at room temperature', '4 years', TRUE),
('Ondansetron', 'Zofran', 'GSK', '4mg', 'Tablet', 'Ondansetron HCl 4mg', 'Antiemetic', '5-HT3 antagonist', 'Prescription', '10 tablets', 185.00, 'Gastrointestinal', 'Nausea, Vomiting', 'Congenital long QT syndrome', 'Headache, Constipation', 'Apomorphine', 'Store at room temperature', '3 years', TRUE),
('Metoclopramide', 'Reglan', 'Pfizer', '10mg', 'Tablet', 'Metoclopramide HCl 10mg', 'Prokinetic', 'Dopamine antagonist', 'Prescription', '30 tablets', 45.00, 'Gastrointestinal', 'Gastroparesis, Nausea', 'GI obstruction, Tardive dyskinesia', 'Drowsiness, Restlessness', 'CNS depressants', 'Store at room temperature', '3 years', TRUE),
('Pantoprazole', 'Protonix', 'Wyeth', '40mg', 'Tablet', 'Pantoprazole sodium 40mg', 'Proton pump inhibitor', 'PPI', 'Prescription', '30 tablets', 125.00, 'Gastrointestinal', 'GERD, Erosive esophagitis', 'Hypersensitivity', 'Headache, Diarrhea', 'Warfarin, Atazanavir', 'Store at room temperature', '3 years', TRUE),
('Docusate', 'Colace', 'Purdue Products', '100mg', 'Capsule', 'Docusate sodium 100mg', 'Stool softener', 'Surfactant laxative', 'OTC', '30 capsules', 25.00, 'Gastrointestinal', 'Constipation', 'Intestinal obstruction', 'Mild cramping', 'Mineral oil', 'Store at room temperature', '3 years', TRUE),
('Famotidine', 'Pepcid', 'Merck', '20mg', 'Tablet', 'Famotidine 20mg', 'Acid reducer', 'H2 receptor antagonist', 'OTC', '30 tablets', 55.00, 'Gastrointestinal', 'Heartburn, Peptic ulcer', 'Hypersensitivity', 'Headache, Dizziness', 'None significant', 'Store at room temperature', '3 years', TRUE),

-- Respiratory (8 medicines)
('Albuterol', 'ProAir', 'Teva', '90mcg/puff', 'Inhaler', 'Albuterol sulfate 90mcg', 'Bronchodilator', 'Beta2-agonist', 'Prescription', '200 puffs', 85.00, 'Respiratory', 'Asthma, COPD', 'Hypersensitivity to albuterol', 'Tremor, Palpitations', 'Beta-blockers', 'Store at room temperature', '3 years', TRUE),
('Budesonide', 'Pulmicort', 'AstraZeneca', '200mcg/puff', 'Inhaler', 'Budesonide 200mcg', 'Anti-inflammatory', 'Inhaled corticosteroid', 'Prescription', '120 puffs', 145.00, 'Respiratory', 'Asthma, COPD', 'Systemic fungal infections', 'Oral thrush, Hoarseness', 'None significant', 'Store at room temperature', '3 years', TRUE),
('Montelukast', 'Singulair', 'Merck', '10mg', 'Tablet', 'Montelukast sodium 10mg', 'Anti-asthmatic', 'Leukotriene antagonist', 'Prescription', '30 tablets', 185.00, 'Respiratory', 'Asthma, Allergic rhinitis', 'Hypersensitivity', 'Headache, Behavioral changes', 'None significant', 'Store at room temperature', '3 years', TRUE),
('Prednisolone', 'Prelone', 'Meda', '5mg', 'Tablet', 'Prednisolone 5mg', 'Anti-inflammatory', 'Corticosteroid', 'Prescription', '30 tablets', 65.00, 'Respiratory', 'Asthma exacerbation, Inflammatory conditions', 'Systemic fungal infections', 'Weight gain, Mood changes', 'NSAIDs, Warfarin', 'Store at room temperature', '3 years', TRUE),
('Theophylline', 'Theo-Dur', 'Key Pharmaceuticals', '200mg', 'Tablet', 'Theophylline anhydrous 200mg', 'Bronchodilator', 'Methylxanthine', 'Prescription', '100 tablets', 75.00, 'Respiratory', 'Asthma, COPD', 'Uncontrolled seizures', 'Nausea, Palpitations', 'Ciprofloxacin, Erythromycin', 'Store at room temperature', '3 years', TRUE),
('Fluticasone', 'Flonase', 'GSK', '50mcg/spray', 'Nasal spray', 'Fluticasone propionate 50mcg', 'Anti-inflammatory', 'Nasal corticosteroid', 'OTC', '120 sprays', 85.00, 'Respiratory', 'Allergic rhinitis, Nasal polyps', 'Recent nasal surgery, Nasal infections', 'Nosebleeds, Nasal irritation', 'None significant', 'Store upright at room temp', '3 years', TRUE),
('Loratadine', 'Claritin', 'Schering-Plough', '10mg', 'Tablet', 'Loratadine 10mg', 'Antihistamine', 'H1 receptor antagonist', 'OTC', '30 tablets', 55.00, 'Respiratory', 'Allergic rhinitis, Urticaria', 'Hypersensitivity', 'Headache, Drowsiness', 'None significant', 'Store at room temperature', '3 years', TRUE),
('Cetirizine', 'Zyrtec', 'Pfizer', '10mg', 'Tablet', 'Cetirizine HCl 10mg', 'Antihistamine', 'H1 receptor antagonist', 'OTC', '30 tablets', 65.00, 'Respiratory', 'Allergic rhinitis, Chronic urticaria', 'End-stage renal disease', 'Drowsiness, Dry mouth', 'None significant', 'Store at room temperature', '3 years', TRUE),

-- Endocrine/Diabetes (7 medicines)
('Metformin', 'Glucophage', 'Bristol Myers Squibb', '500mg', 'Tablet', 'Metformin HCl 500mg', 'Antidiabetic', 'Biguanide', 'Prescription', '60 tablets', 45.00, 'Endocrine', 'Type 2 diabetes', 'Severe renal impairment, Metabolic acidosis', 'GI upset, Lactic acidosis', 'Contrast dye, Alcohol', 'Store at room temperature', '3 years', TRUE),
('Insulin glargine', 'Lantus', 'Sanofi', '100 units/ml', 'Injection', 'Insulin glargine 100 units/ml', 'Antidiabetic', 'Long-acting insulin', 'Prescription', '10ml vial', 285.00, 'Endocrine', 'Type 1 diabetes, Type 2 diabetes', 'Hypoglycemia', 'Hypoglycemia, Injection site reactions', 'Alcohol, Beta-blockers', 'Refrigerate, do not freeze', '28 days after opening', TRUE),
('Gliclazide', 'Diamicron', 'Servier', '80mg', 'Tablet', 'Gliclazide 80mg', 'Antidiabetic', 'Sulfonylurea', 'Prescription', '30 tablets', 75.00, 'Endocrine', 'Type 2 diabetes', 'Type 1 diabetes, Severe renal impairment', 'Hypoglycemia, Weight gain', 'Alcohol, NSAIDs', 'Store at room temperature', '3 years', TRUE),
('Levothyroxine', 'Synthroid', 'Abbott', '100mcg', 'Tablet', 'Levothyroxine sodium 100mcg', 'Thyroid hormone', 'T4 replacement', 'Prescription', '30 tablets', 95.00, 'Endocrine', 'Hypothyroidism', 'Hyperthyroidism, Acute MI', 'Palpitations, Insomnia', 'Warfarin, Iron', 'Store at room temperature', '3 years', TRUE),
('Prednisone', 'Deltasone', 'Pfizer', '10mg', 'Tablet', 'Prednisone 10mg', 'Anti-inflammatory', 'Corticosteroid', 'Prescription', '30 tablets', 55.00, 'Endocrine', 'Inflammatory conditions, Allergic reactions', 'Systemic fungal infections', 'Weight gain, Mood changes', 'NSAIDs, Vaccines', 'Store at room temperature', '3 years', TRUE),
('Glipizide', 'Glucotrol', 'Pfizer', '5mg', 'Tablet', 'Glipizide 5mg', 'Antidiabetic', 'Sulfonylurea', 'Prescription', '30 tablets', 65.00, 'Endocrine', 'Type 2 diabetes', 'Type 1 diabetes, Diabetic ketoacidosis', 'Hypoglycemia, Weight gain', 'Alcohol, Beta-blockers', 'Store at room temperature', '3 years', TRUE),
('Pioglitazone', 'Actos', 'Takeda', '15mg', 'Tablet', 'Pioglitazone HCl 15mg', 'Antidiabetic', 'Thiazolidinedione', 'Prescription', '30 tablets', 185.00, 'Endocrine', 'Type 2 diabetes', 'Heart failure, Bladder cancer', 'Weight gain, Edema', 'Insulin', 'Store at room temperature', '3 years', TRUE),

-- Neurological/Psychiatric (10 medicines)
('Carbamazepine', 'Tegretol', 'Novartis', '200mg', 'Tablet', 'Carbamazepine 200mg', 'Anticonvulsant', 'Sodium channel blocker', 'Prescription', '100 tablets', 125.00, 'Neurological', 'Seizures, Trigeminal neuralgia', 'AV block, Bone marrow suppression', 'Drowsiness, Diplopia', 'Warfarin, Oral contraceptives', 'Store at room temperature', '3 years', TRUE),
('Phenytoin', 'Dilantin', 'Pfizer', '100mg', 'Capsule', 'Phenytoin sodium 100mg', 'Anticonvulsant', 'Sodium channel blocker', 'Prescription', '30 capsules', 85.00, 'Neurological', 'Seizures', 'Heart block, Hypersensitivity', 'Gingival hyperplasia, Hirsutism', 'Warfarin, Oral contraceptives', 'Store at room temperature', '3 years', TRUE),
('Levodopa/Carbidopa', 'Sinemet', 'Merck', '25/100mg', 'Tablet', 'Carbidopa 25mg/Levodopa 100mg', 'Antiparkinson', 'Dopamine precursor', 'Prescription', '100 tablets', 195.00, 'Neurological', 'Parkinson disease', 'Narrow-angle glaucoma, MAO inhibitor use', 'Dyskinesia, Nausea', 'MAO inhibitors, Iron', 'Store at room temperature', '3 years', TRUE),
('Fluoxetine', 'Prozac', 'Lilly', '20mg', 'Capsule', 'Fluoxetine HCl 20mg', 'Antidepressant', 'SSRI', 'Prescription', '30 capsules', 125.00, 'Psychiatric', 'Depression, OCD, Bulimia', 'MAO inhibitor use, Thioridazine use', 'Insomnia, Nausea', 'MAO inhibitors, Phenytoin', 'Store at room temperature', '3 years', TRUE),
('Sertraline', 'Zoloft', 'Pfizer', '50mg', 'Tablet', 'Sertraline HCl 50mg', 'Antidepressant', 'SSRI', 'Prescription', '30 tablets', 135.00, 'Psychiatric', 'Depression, Panic disorder, PTSD', 'MAO inhibitor use', 'Nausea, Sexual dysfunction', 'MAO inhibitors, Warfarin', 'Store at room temperature', '3 years', TRUE),
('Risperidone', 'Risperdal', 'Janssen', '2mg', 'Tablet', 'Risperidone 2mg', 'Antipsychotic', 'Atypical antipsychotic', 'Prescription', '30 tablets', 185.00, 'Psychiatric', 'Schizophrenia, Bipolar disorder', 'Hypersensitivity', 'Extrapyramidal symptoms, Weight gain', 'CNS depressants', 'Store at room temperature', '3 years', TRUE),
('Lithium', 'Lithobid', 'Solvay', '300mg', 'Tablet', 'Lithium carbonate 300mg', 'Mood stabilizer', 'Alkali metal', 'Prescription', '100 tablets', 95.00, 'Psychiatric', 'Bipolar disorder, Mania', 'Severe renal disease, Severe cardiac disease', 'Tremor, Polyuria', 'NSAIDs, Diuretics', 'Store at room temperature', '3 years', TRUE),
('Alprazolam', 'Xanax', 'Pfizer', '0.5mg', 'Tablet', 'Alprazolam 0.5mg', 'Anxiolytic', 'Benzodiazepine', 'Schedule IV', '30 tablets', 85.00, 'Psychiatric', 'Anxiety disorders, Panic disorder', 'Narrow-angle glaucoma, Pregnancy', 'Drowsiness, Memory impairment', 'Alcohol, Ketoconazole', 'Store at room temperature', '3 years', TRUE),
('Lorazepam', 'Ativan', 'Wyeth', '1mg', 'Tablet', 'Lorazepam 1mg', 'Anxiolytic', 'Benzodiazepine', 'Schedule IV', '30 tablets', 65.00, 'Psychiatric', 'Anxiety, Insomnia', 'Myasthenia gravis, Severe respiratory disease', 'Drowsiness, Confusion', 'Alcohol, CNS depressants', 'Store at room temperature', '3 years', TRUE),
('Gabapentin', 'Neurontin', 'Pfizer', '300mg', 'Capsule', 'Gabapentin 300mg', 'Anticonvulsant', 'GABA analog', 'Prescription', '90 capsules', 145.00, 'Neurological', 'Seizures, Neuropathic pain', 'Hypersensitivity', 'Drowsiness, Dizziness', 'Antacids', 'Store at room temperature', '3 years', TRUE),

-- Miscellaneous Essential (15 medicines)
('Acyclovir', 'Zovirax', 'GSK', '400mg', 'Tablet', 'Acyclovir 400mg', 'Antiviral', 'Nucleoside analog', 'Prescription', '30 tablets', 185.00, 'Antiviral', 'Herpes simplex, Varicella zoster', 'Hypersensitivity to acyclovir', 'Nausea, Diarrhea', 'Probenecid', 'Store at room temperature', '3 years', TRUE),
('Diphenhydramine', 'Benadryl', 'Johnson & Johnson', '25mg', 'Capsule', 'Diphenhydramine HCl 25mg', 'Antihistamine', 'H1 receptor antagonist', 'OTC', '24 capsules', 35.00, 'Allergy', 'Allergic reactions, Insomnia', 'Narrow-angle glaucoma, BPH', 'Drowsiness, Dry mouth', 'MAO inhibitors, Alcohol', 'Store at room temperature', '3 years', TRUE),
('Hydrocortisone', 'Cortef', 'Pfizer', '10mg', 'Tablet', 'Hydrocortisone 10mg', 'Anti-inflammatory', 'Corticosteroid', 'Prescription', '30 tablets', 75.00, 'Anti-inflammatory', 'Adrenal insufficiency, Inflammation', 'Systemic fungal infections', 'Fluid retention, Mood changes', 'NSAIDs, Vaccines', 'Store at room temperature', '3 years', TRUE),
('Cholecalciferol', 'Vitamin D3', 'Nature Made', '1000 IU', 'Tablet', 'Cholecalciferol 1000 IU', 'Vitamin supplement', 'Fat-soluble vitamin', 'OTC', '100 tablets', 25.00, 'Supplement', 'Vitamin D deficiency', 'Hypercalcemia', 'Hypercalcemia (high doses)', 'Thiazide diuretics', 'Store at room temperature', '3 years', TRUE),
('Folic acid', 'Folate', 'Generic', '5mg', 'Tablet', 'Folic acid 5mg', 'Vitamin supplement', 'B vitamin', 'Prescription', '30 tablets', 15.00, 'Supplement', 'Folate deficiency, Pregnancy', 'B12 deficiency', 'Generally well tolerated', 'Methotrexate, Phenytoin', 'Store at room temperature', '3 years', TRUE),
('Iron sulfate', 'Ferrous sulfate', 'Generic', '325mg', 'Tablet', 'Ferrous sulfate 325mg', 'Iron supplement', 'Essential mineral', 'OTC', '100 tablets', 25.00, 'Supplement', 'Iron deficiency anemia', 'Hemochromatosis', 'Constipation, GI upset', 'Levothyroxine, Quinolones', 'Store at room temperature', '3 years', TRUE),
('Multivitamin', 'Centrum', 'Pfizer', 'Daily dose', 'Tablet', 'Multiple vitamins and minerals', 'Vitamin supplement', 'Multivitamin/mineral', 'OTC', '30 tablets', 45.00, 'Supplement', 'Nutritional supplementation', 'Hypervitaminosis', 'Generally well tolerated', 'Warfarin (Vitamin K)', 'Store at room temperature', '3 years', TRUE),
('Calcium carbonate', 'Tums', 'GSK', '500mg', 'Tablet', 'Calcium carbonate 500mg', 'Antacid/Supplement', 'Alkaline earth metal', 'OTC', '60 tablets', 25.00, 'Antacid', 'Heartburn, Calcium deficiency', 'Hypercalcemia', 'Constipation, Kidney stones', 'Iron, Tetracyclines', 'Store at room temperature', '3 years', TRUE),
('Magnesium oxide', 'Mag-Ox', 'Blaine', '400mg', 'Tablet', 'Magnesium oxide 400mg', 'Laxative/Supplement', 'Alkaline earth metal', 'OTC', '60 tablets', 35.00, 'Supplement', 'Magnesium deficiency, Constipation', 'Severe renal impairment', 'Diarrhea, Cramping', 'Tetracyclines, Quinolones', 'Store at room temperature', '3 years', TRUE),
('Potassium chloride', 'K-Dur', 'Schering', '10mEq', 'Tablet', 'Potassium chloride 10mEq', 'Electrolyte supplement', 'Essential mineral', 'Prescription', '30 tablets', 75.00, 'Supplement', 'Hypokalemia', 'Hyperkalemia, Severe renal impairment', 'GI upset, Hyperkalemia', 'ACE inhibitors, Potassium-sparing diuretics', 'Store at room temperature', '3 years', TRUE),
('Zinc sulfate', 'Zinc', 'Generic', '220mg', 'Tablet', 'Zinc sulfate 220mg', 'Mineral supplement', 'Essential trace element', 'OTC', '100 tablets', 25.00, 'Supplement', 'Zinc deficiency', 'Wilson disease', 'GI upset, Metallic taste', 'Quinolones, Tetracyclines', 'Store at room temperature', '3 years', TRUE),
('Melatonin', 'Sleep aid', 'Nature Made', '3mg', 'Tablet', 'Melatonin 3mg', 'Sleep aid', 'Hormone supplement', 'OTC', '30 tablets', 35.00, 'Sleep aid', 'Insomnia, Jet lag', 'Autoimmune disorders', 'Drowsiness, Vivid dreams', 'Warfarin, Immunosuppressants', 'Store at room temperature', '3 years', TRUE),
('Epinephrine', 'EpiPen', 'Mylan', '0.3mg', 'Auto-injector', 'Epinephrine 0.3mg/0.3ml', 'Emergency medication', 'Sympathomimetic', 'Prescription', '2 auto-injectors', 685.00, 'Emergency', 'Anaphylaxis, Severe allergic reactions', 'None in emergency', 'Palpitations, Anxiety', 'Beta-blockers', 'Store at room temperature', '18 months', TRUE),
('Naloxone', 'Narcan', 'Emergent BioSolutions', '4mg', 'Nasal spray', 'Naloxone HCl 4mg/0.1ml', 'Opioid antagonist', 'Competitive antagonist', 'OTC', '2 nasal sprays', 45.00, 'Emergency', 'Opioid overdose', 'None in emergency', 'Precipitation of withdrawal', 'None in emergency', 'Store at room temperature', '3 years', TRUE),
('Dextrose', 'D50W', 'Hospira', '50%', 'Injection', 'Dextrose 50% (25g/50ml)', 'Antihypoglycemic', 'Simple sugar', 'Prescription', '50ml vial', 25.00, 'Emergency', 'Hypoglycemia', 'Hyperglycemia', 'Hyperglycemia', 'None', 'Store at room temperature', '3 years', TRUE);

-- Complete the insert statement
SELECT 'Medicine master database populated with 100 essential medicines' as result;